const canvas=document.querySelector('#map'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),ui={level:$('#level'),score:$('#score'),timer:$('#timer'),lives:$('#lives'),mission:$('#mission'),intro:$('#intro'),result:$('#result'),toast:$('#toast'),title:$('#result-title'),resultScore:$('#result-score'),resultText:$('#result-text')};
const TOTAL=24,DURATION=150,palette=['#d75f55','#397d9b','#d6a02d','#75549a','#58768e','#b6a04b'],levelColors=palette.slice(0,4);
let vw=0,vh=0,dpr=1,worldW=0,worldH=0,camX=0,camY=0,playing=false,lives=3,found=0,timeLeft=DURATION,cats=[],timerId,toastId,level=1,nextNumber=1,activeColor=null,completedColors=[],lastWon=false,retryKeepsLives=false;
let pointer={down:false,x:0,y:0,lastX:0,lastY:0,moved:0};
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hash=(x,y,s=0)=>{const n=Math.sin(x*127.1+y*311.7+s*74.7)*43758.5453;return n-Math.floor(n)};
function resize(){dpr=Math.min(devicePixelRatio||1,2);vw=innerWidth;vh=innerHeight;worldW=vw*4;worldH=vh*4;canvas.width=vw*dpr;canvas.height=vh*dpr;canvas.style.width=vw+'px';canvas.style.height=vh+'px';camX=clamp(camX,0,worldW-vw);camY=clamp(camY,0,worldH-vh);draw()}
function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function tree(x,y,s=1){ctx.fillStyle='#614b36';ctx.fillRect(x-3*s,y,6*s,15*s);ctx.fillStyle='#52765b';ctx.beginPath();ctx.arc(x,y-7*s,13*s,0,7);ctx.fill();ctx.fillStyle='#719069';ctx.beginPath();ctx.arc(x-7*s,y-10*s,7*s,0,7);ctx.fill()}
function building(x,y,w,h,color,label){ctx.fillStyle='#413b35';rounded(x+4,y+6,w,h,6);ctx.fill();ctx.fillStyle=color;rounded(x,y,w,h,6);ctx.fill();ctx.fillStyle='#fff0cf';for(let i=12;i<w-10;i+=24)ctx.fillRect(x+i,y+15,10,13);ctx.fillStyle='#3d5a50';ctx.fillRect(x+w/2-7,y+h-22,14,22);if(label){ctx.fillStyle='#fffaf0';rounded(x+7,y-12,w-14,20,5);ctx.fill();ctx.fillStyle='#25463c';ctx.font='700 10px system-ui';ctx.textAlign='center';ctx.fillText(label,x+w/2,y+2)}}
function drawPark(x,y,w,h){ctx.fillStyle='#8fb07a';rounded(x,y,w,h,18);ctx.fill();ctx.strokeStyle='#e7d5aa';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(x+10,y+h*.7);ctx.quadraticCurveTo(x+w*.55,y+h*.25,x+w-10,y+h*.45);ctx.stroke();for(let i=0;i<9;i++)tree(x+20+hash(i,2)*Math.max(20,w-40),y+20+hash(i,9)*Math.max(20,h-40),.7);ctx.fillStyle='#b97750';ctx.fillRect(x+w*.48,y+h*.55,36,7)}
function drawField(x,y,w,h){ctx.fillStyle='#719c70';rounded(x,y,w,h,10);ctx.fill();ctx.strokeStyle='#f7efd4';ctx.lineWidth=3;ctx.strokeRect(x+9,y+9,w-18,h-18);ctx.beginPath();ctx.moveTo(x+w/2,y+9);ctx.lineTo(x+w/2,y+h-9);ctx.stroke();ctx.beginPath();ctx.arc(x+w/2,y+h/2,Math.min(w,h)*.16,0,7);ctx.stroke()}
function drawWorld(){ctx.fillStyle='#d7ccaa';ctx.fillRect(0,0,worldW,worldH);const roadW=Math.max(72,Math.min(vw,vh)*.14),blockW=worldW/4,blockH=worldH/4;ctx.fillStyle='#777a72';for(let i=0;i<=4;i++){ctx.fillRect(i*blockW-roadW/2,0,roadW,worldH);ctx.fillRect(0,i*blockH-roadW/2,worldW,roadW)}ctx.strokeStyle='#e9d899';ctx.lineWidth=2;ctx.setLineDash([16,16]);for(let i=0;i<=4;i++){ctx.beginPath();ctx.moveTo(i*blockW,0);ctx.lineTo(i*blockW,worldH);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*blockH);ctx.lineTo(worldW,i*blockH);ctx.stroke()}ctx.setLineDash([]);for(let gy=0;gy<4;gy++)for(let gx=0;gx<4;gx++){const x=gx*blockW+roadW*.62,y=gy*blockH+roadW*.62,w=blockW-roadW*1.24,h=blockH-roadW*1.24,k=gy*4+gx;if(k===5)drawPark(x,y,w,h);else if(k===10||k===14)drawField(x,y,w,h);else{const labels=k===1?['FARMACIA','CASA','CASA']:k===7?['PANADERÍA','CASA','CASA']:k===12?['COLEGIO','COLEGIO','CASA']:['CASA','CASA','CASA'],bw=Math.max(58,w*.25),bh=Math.max(48,h*.22);for(let j=0;j<3;j++)building(x+12+(j%2)*(w-bw-24),y+16+Math.floor(j/2)*(h-bh-27),bw,bh,['#c86d5b','#d79a58','#769587'][j],labels[j]);for(let j=0;j<6;j++)tree(x+hash(k,j)*w,y+hash(j,k,3)*h,.65)}}cats.forEach(c=>{if(!c.found)drawCat(c)})}
function drawCat(c){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.r);ctx.globalAlpha=.72;ctx.fillStyle=c.color;ctx.beginPath();ctx.ellipse(0,3,10,14,0,0,7);ctx.fill();ctx.beginPath();ctx.arc(0,-10,9,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-8,-15);ctx.lineTo(-7,-24);ctx.lineTo(-1,-17);ctx.moveTo(8,-15);ctx.lineTo(7,-24);ctx.lineTo(1,-17);ctx.fill();ctx.strokeStyle=c.color;ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.arc(10,7,11,-1.3,1.2);ctx.stroke();ctx.fillStyle='#1d352f';ctx.beginPath();ctx.arc(-3,-10,1.5,0,7);ctx.arc(3,-10,1.5,0,7);ctx.fill();if(level===2){ctx.globalAlpha=1;ctx.fillStyle='#fff9e9';ctx.beginPath();ctx.arc(0,3,8,0,7);ctx.fill();ctx.fillStyle='#173f35';ctx.font='900 9px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(c.num,0,3)}ctx.restore()}
function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,vw,vh);ctx.save();ctx.translate(-camX,-camY);drawWorld();ctx.restore()}
function placeCats(){cats=[];const margin=45;for(let i=0;i<TOTAL;i++){let x,y,tries=0;do{x=rand(margin,worldW-margin);y=rand(margin,worldH-margin);tries++}while(cats.some(c=>Math.hypot(c.x-x,c.y-y)<75)&&tries<80);cats.push({x,y,r:rand(-.5,.5),num:i+1,color:level===3?levelColors[Math.floor(i/6)]:palette[i%palette.length],found:false})}}
function updateHud(){ui.level.textContent=`${level} / 3`;ui.score.textContent=`${found} / ${TOTAL}`;ui.lives.textContent=lives?Array(lives).fill('♥').join(' '):'—';ui.timer.textContent=`${Math.floor(timeLeft/60)}:${String(timeLeft%60).padStart(2,'0')}`;if(level===1)ui.mission.textContent='Nivel 1 · Encuentra cualquier gatito';if(level===2)ui.mission.textContent=`Nivel 2 · Busca ahora el gato ${nextNumber}`;if(level===3)ui.mission.textContent=activeColor?`Nivel 3 · Completa este color (${cats.filter(c=>c.found&&c.color===activeColor).length}/6)`:`Nivel 3 · Elige el próximo color (${completedColors.length}/4)`}
function toast(msg){clearTimeout(toastId);ui.toast.textContent=msg;ui.toast.classList.add('show');toastId=setTimeout(()=>ui.toast.classList.remove('show'),1300)}
function start(preserveLives=false){clearInterval(timerId);playing=true;if(!preserveLives)lives=3;found=0;timeLeft=DURATION;nextNumber=1;activeColor=null;completedColors=[];lastWon=false;retryKeepsLives=false;camX=worldW/2-vw/2;camY=worldH/2-vh/2;placeCats();updateHud();draw();ui.intro.classList.remove('visible');ui.result.classList.remove('visible');timerId=setInterval(()=>{timeLeft--;updateHud();if(timeLeft<=0)timeExpired()},1000);toast(level===1?'Encuentra los 24 gatos':level===2?'Empieza por el gato 1':'El primer gato decide el primer color')}
function timeExpired(){clearInterval(timerId);playing=false;lives--;updateHud();if(lives<=0){end(false);return}lastWon=false;retryKeepsLives=true;ui.title.classList.remove('win');ui.title.textContent='VIDA PERDIDA';$('#result-kicker').textContent=`SE ACABÓ EL TIEMPO · NIVEL ${level}`;ui.resultScore.innerHTML=`${found}<span>/${TOTAL}</span>`;ui.resultText.textContent=`Te ${lives===1?'queda 1 vida':`quedan ${lives} vidas`}. El nivel se reiniciará con gatos en posiciones nuevas.`;$('#restartBtn').textContent=`Reintentar nivel ${level}`;ui.result.classList.add('visible')}
function end(won){playing=false;lastWon=won;retryKeepsLives=false;clearInterval(timerId);ui.title.classList.toggle('win',won);const nextRule=level===1?'Ahora los gatos están numerados: recógelos del 1 al 24. Un error cuesta una vida.':'Hay cuatro colores. El primer gato elige el color y debes completar sus seis gatos antes de cambiar.';if(won&&level<3){ui.title.textContent=`NIVEL ${level+1}`;$('#result-kicker').textContent='PREPÁRATE';ui.resultText.textContent=nextRule;$('#restartBtn').textContent=`Empezar nivel ${level+1}`}else if(won){ui.title.textContent='¡RETO COMPLETADO!';$('#result-kicker').textContent='LOS TRES NIVELES SUPERADOS';ui.resultText.textContent='Has dominado los tres niveles. ¡Todo el barrio ronronea!';$('#restartBtn').textContent='Jugar desde el nivel 1'}else{ui.title.textContent='GAME OVER';$('#result-kicker').textContent=`NIVEL ${level}`;ui.resultText.textContent='Te has quedado sin vidas. El nivel volverá a empezar con tres vidas.';$('#restartBtn').textContent='Repetir nivel'}ui.resultScore.innerHTML=`${found}<span>/${TOTAL}</span>`;ui.result.classList.add('visible')}
function loseLife(msg){lives--;updateHud();navigator.vibrate?.(80);toast(msg);if(lives<=0)end(false)}
function tap(sx,sy){if(!playing)return;const wx=sx+camX,wy=sy+camY,hit=cats.find(c=>!c.found&&Math.hypot(c.x-wx,c.y-wy)<25);if(!hit){loseLife('Aquí no hay gato · pierdes una vida');return}if(level===2&&hit.num!==nextNumber){loseLife(`Ese no es el ${nextNumber} · pierdes una vida`);return}if(level===3&&activeColor&&hit.color!==activeColor){loseLife('Termina primero el color elegido');return}if(level===3&&!activeColor)activeColor=hit.color;hit.found=true;found++;if(level===2)nextNumber++;if(level===3&&cats.filter(c=>c.found&&c.color===activeColor).length===6){completedColors.push(activeColor);activeColor=null;toast(found===TOTAL?'¡Último color completo!':'¡Color completo! Elige el siguiente')}else toast(found===TOTAL?'¡Último gatito!':'¡Miau! Gatito encontrado');updateHud();draw();if(found===TOTAL)end(true)}
canvas.addEventListener('pointerdown',e=>{pointer={down:true,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:0};canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging')});
canvas.addEventListener('pointermove',e=>{if(!pointer.down)return;const dx=e.clientX-pointer.lastX,dy=e.clientY-pointer.lastY;pointer.moved+=Math.hypot(dx,dy);camX=clamp(camX-dx,0,worldW-vw);camY=clamp(camY-dy,0,worldH-vh);pointer.lastX=e.clientX;pointer.lastY=e.clientY;draw()});
canvas.addEventListener('pointerup',e=>{if(pointer.down&&pointer.moved<9)tap(e.clientX,e.clientY);pointer.down=false;canvas.classList.remove('dragging')});
$('#startBtn').onclick=()=>start();$('#restartBtn').onclick=()=>{if(lastWon)level=level<3?level+1:1;start(retryKeepsLives)};$('#helpBtn').onclick=()=>{ui.intro.classList.add('visible');$('#startBtn').textContent=playing?'Seguir jugando':'Empezar la búsqueda'};
addEventListener('resize',resize);resize();placeCats();draw();updateHud();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');

